fan_set_buzzer_on:
  description: Turn the buzzer on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_buzzer_off:
  description: Turn the buzzer off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_led_on:
  description: Turn the led on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_led_off:
  description: Turn the led off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_child_lock_on:
  description: Turn the child lock on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_child_lock_off:
  description: Turn the child lock off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_favorite_level:
  description: Set the favorite level.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"
    level:
      description: Level, between 0 and 16.
      example: 1

fan_set_fan_level:
  description: Set the fan level.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"
    level:
      description: Level, between 1 and 3.
      example: 1

fan_set_led_brightness:
  description: Set the led brightness.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"
    brightness:
      description: Brightness (0 = Bright, 1 = Dim, 2 = Off)
      example: 1

fan_set_auto_detect_on:
  description: Turn the auto detect on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_auto_detect_off:
  description: Turn the auto detect off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_learn_mode_on:
  description: Turn the learn mode on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_learn_mode_off:
  description: Turn the learn mode off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_volume:
  description: Set the sound volume.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"
    volume:
      description: Volume, between 0 and 100.
      example: 50

fan_reset_filter:
  description: Reset the filter lifetime and usage.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_extra_features:
  description: Manipulates a storage register which advertises extra features. The Mi Home app evaluates the value. A feature called "turbo mode" is unlocked in the app on value 1.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"
    features:
      description: Integer, known values are 0 (default) and 1 (turbo mode).
      example: 1

fan_set_target_humidity:
  description: Set the target humidity.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"
    humidity:
      description: Target humidity. Allowed values are 30, 40, 50, 60, 70 and 80.
      example: 50

fan_set_dry_on:
  description: Turn the dry mode on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_dry_off:
  description: Turn the dry mode off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"

fan_set_filters_cleaned:
  description: Inform the device that filters are cleaned.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: "xiaomi_miio_airpurifier.xiaomi_miio_device"
